package com.pinganzhiyuan.model;

public class H5AppDownloadLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app_download_log.id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app_download_log.user_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app_download_log.ip
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app_download_log.h5_client_version_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private Long h5ClientVersionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app_download_log.app_client_version_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private Long appClientVersionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app_download_log.user_agent
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private String userAgent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app_download_log.id
	 * @return  the value of h5_app_download_log.id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app_download_log.id
	 * @param id  the value for h5_app_download_log.id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app_download_log.user_id
	 * @return  the value of h5_app_download_log.user_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app_download_log.user_id
	 * @param userId  the value for h5_app_download_log.user_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app_download_log.ip
	 * @return  the value of h5_app_download_log.ip
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app_download_log.ip
	 * @param ip  the value for h5_app_download_log.ip
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app_download_log.h5_client_version_id
	 * @return  the value of h5_app_download_log.h5_client_version_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public Long getH5ClientVersionId() {
		return h5ClientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app_download_log.h5_client_version_id
	 * @param h5ClientVersionId  the value for h5_app_download_log.h5_client_version_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setH5ClientVersionId(Long h5ClientVersionId) {
		this.h5ClientVersionId = h5ClientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app_download_log.app_client_version_id
	 * @return  the value of h5_app_download_log.app_client_version_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public Long getAppClientVersionId() {
		return appClientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app_download_log.app_client_version_id
	 * @param appClientVersionId  the value for h5_app_download_log.app_client_version_id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setAppClientVersionId(Long appClientVersionId) {
		this.appClientVersionId = appClientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app_download_log.user_agent
	 * @return  the value of h5_app_download_log.user_agent
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public String getUserAgent() {
		return userAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app_download_log.user_agent
	 * @param userAgent  the value for h5_app_download_log.user_agent
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}
}