package com.pinganzhiyuan.model;

public class H5AppClient {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app.id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app.name
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app.note
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_app.url
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app.id
	 * @return  the value of h5_app.id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app.id
	 * @param id  the value for h5_app.id
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app.name
	 * @return  the value of h5_app.name
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app.name
	 * @param name  the value for h5_app.name
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app.note
	 * @return  the value of h5_app.note
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app.note
	 * @param note  the value for h5_app.note
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_app.url
	 * @return  the value of h5_app.url
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_app.url
	 * @param url  the value for h5_app.url
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	public void setUrl(String url) {
		this.url = url;
	}
}