package com.pinganzhiyuan.model;

public class H5ClientColumnMapping {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_column_mapping.id
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_column_mapping.h5_column_key
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	private String h5ColumnKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_column_mapping.h5_client_version_id
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	private Long h5ClientVersionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_column_mapping.status
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_column_mapping.id
	 * @return  the value of h5_client_column_mapping.id
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_column_mapping.id
	 * @param id  the value for h5_client_column_mapping.id
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_column_mapping.h5_column_key
	 * @return  the value of h5_client_column_mapping.h5_column_key
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public String getH5ColumnKey() {
		return h5ColumnKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_column_mapping.h5_column_key
	 * @param h5ColumnKey  the value for h5_client_column_mapping.h5_column_key
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public void setH5ColumnKey(String h5ColumnKey) {
		this.h5ColumnKey = h5ColumnKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_column_mapping.h5_client_version_id
	 * @return  the value of h5_client_column_mapping.h5_client_version_id
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public Long getH5ClientVersionId() {
		return h5ClientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_column_mapping.h5_client_version_id
	 * @param h5ClientVersionId  the value for h5_client_column_mapping.h5_client_version_id
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public void setH5ClientVersionId(Long h5ClientVersionId) {
		this.h5ClientVersionId = h5ClientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_column_mapping.status
	 * @return  the value of h5_client_column_mapping.status
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_column_mapping.status
	 * @param status  the value for h5_client_column_mapping.status
	 * @mbg.generated  Fri Mar 23 10:35:07 CST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}