package com.pinganzhiyuan.model;

import java.util.Date;

public class H5ClientVersion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.name
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.logo_url
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private String logoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.change_log
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private String changeLog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.page_type
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Byte pageType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.client_version_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Long clientVersionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.h5_channel_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Long h5ChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.h5_app_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Long h5AppId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.platform_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Byte platformId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.is_published
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Boolean isPublished;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h5_client_version.publish_time
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	private Date publishTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.id
	 * @return  the value of h5_client_version.id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.id
	 * @param id  the value for h5_client_version.id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.name
	 * @return  the value of h5_client_version.name
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.name
	 * @param name  the value for h5_client_version.name
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.logo_url
	 * @return  the value of h5_client_version.logo_url
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public String getLogoUrl() {
		return logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.logo_url
	 * @param logoUrl  the value for h5_client_version.logo_url
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.change_log
	 * @return  the value of h5_client_version.change_log
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public String getChangeLog() {
		return changeLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.change_log
	 * @param changeLog  the value for h5_client_version.change_log
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setChangeLog(String changeLog) {
		this.changeLog = changeLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.page_type
	 * @return  the value of h5_client_version.page_type
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Byte getPageType() {
		return pageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.page_type
	 * @param pageType  the value for h5_client_version.page_type
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setPageType(Byte pageType) {
		this.pageType = pageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.client_version_id
	 * @return  the value of h5_client_version.client_version_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Long getClientVersionId() {
		return clientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.client_version_id
	 * @param clientVersionId  the value for h5_client_version.client_version_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setClientVersionId(Long clientVersionId) {
		this.clientVersionId = clientVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.h5_channel_id
	 * @return  the value of h5_client_version.h5_channel_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Long getH5ChannelId() {
		return h5ChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.h5_channel_id
	 * @param h5ChannelId  the value for h5_client_version.h5_channel_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setH5ChannelId(Long h5ChannelId) {
		this.h5ChannelId = h5ChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.h5_app_id
	 * @return  the value of h5_client_version.h5_app_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Long getH5AppId() {
		return h5AppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.h5_app_id
	 * @param h5AppId  the value for h5_client_version.h5_app_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setH5AppId(Long h5AppId) {
		this.h5AppId = h5AppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.platform_id
	 * @return  the value of h5_client_version.platform_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Byte getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.platform_id
	 * @param platformId  the value for h5_client_version.platform_id
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setPlatformId(Byte platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.is_published
	 * @return  the value of h5_client_version.is_published
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Boolean getIsPublished() {
		return isPublished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.is_published
	 * @param isPublished  the value for h5_client_version.is_published
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setIsPublished(Boolean isPublished) {
		this.isPublished = isPublished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h5_client_version.publish_time
	 * @return  the value of h5_client_version.publish_time
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public Date getPublishTime() {
		return publishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h5_client_version.publish_time
	 * @param publishTime  the value for h5_client_version.publish_time
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}
}