package com.pinganzhiyuan.model;

public class Nav {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nav.id
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nav.title
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nav.icon_url
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nav.target_url
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    private String targetUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nav.id
     *
     * @return the value of nav.id
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nav.id
     *
     * @param id the value for nav.id
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nav.title
     *
     * @return the value of nav.title
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nav.title
     *
     * @param title the value for nav.title
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nav.icon_url
     *
     * @return the value of nav.icon_url
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nav.icon_url
     *
     * @param iconUrl the value for nav.icon_url
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nav.target_url
     *
     * @return the value of nav.target_url
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public String getTargetUrl() {
        return targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nav.target_url
     *
     * @param targetUrl the value for nav.target_url
     *
     * @mbg.generated Thu Dec 07 14:54:02 CST 2017
     */
    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
    }
}