package com.pinganzhiyuan.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNull() {
            addCriterion("subtitle is null");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNotNull() {
            addCriterion("subtitle is not null");
            return (Criteria) this;
        }

        public Criteria andSubtitleEqualTo(String value) {
            addCriterion("subtitle =", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotEqualTo(String value) {
            addCriterion("subtitle <>", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThan(String value) {
            addCriterion("subtitle >", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("subtitle >=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThan(String value) {
            addCriterion("subtitle <", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThanOrEqualTo(String value) {
            addCriterion("subtitle <=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLike(String value) {
            addCriterion("subtitle like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotLike(String value) {
            addCriterion("subtitle not like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleIn(List<String> values) {
            addCriterion("subtitle in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotIn(List<String> values) {
            addCriterion("subtitle not in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleBetween(String value1, String value2) {
            addCriterion("subtitle between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotBetween(String value1, String value2) {
            addCriterion("subtitle not between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIsNull() {
            addCriterion("is_published is null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIsNotNull() {
            addCriterion("is_published is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedEqualTo(Boolean value) {
            addCriterion("is_published =", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotEqualTo(Boolean value) {
            addCriterion("is_published <>", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedGreaterThan(Boolean value) {
            addCriterion("is_published >", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_published >=", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedLessThan(Boolean value) {
            addCriterion("is_published <", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_published <=", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIn(List<Boolean> values) {
            addCriterion("is_published in", values, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotIn(List<Boolean> values) {
            addCriterion("is_published not in", values, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published between", value1, value2, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published not between", value1, value2, "isPublished");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNull() {
            addCriterion("img_url is null");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNotNull() {
            addCriterion("img_url is not null");
            return (Criteria) this;
        }

        public Criteria andImgUrlEqualTo(String value) {
            addCriterion("img_url =", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotEqualTo(String value) {
            addCriterion("img_url <>", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThan(String value) {
            addCriterion("img_url >", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("img_url >=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThan(String value) {
            addCriterion("img_url <", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThanOrEqualTo(String value) {
            addCriterion("img_url <=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLike(String value) {
            addCriterion("img_url like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotLike(String value) {
            addCriterion("img_url not like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlIn(List<String> values) {
            addCriterion("img_url in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotIn(List<String> values) {
            addCriterion("img_url not in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlBetween(String value1, String value2) {
            addCriterion("img_url between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotBetween(String value1, String value2) {
            addCriterion("img_url not between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andLightTitleIsNull() {
            addCriterion("light_title is null");
            return (Criteria) this;
        }

        public Criteria andLightTitleIsNotNull() {
            addCriterion("light_title is not null");
            return (Criteria) this;
        }

        public Criteria andLightTitleEqualTo(String value) {
            addCriterion("light_title =", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotEqualTo(String value) {
            addCriterion("light_title <>", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleGreaterThan(String value) {
            addCriterion("light_title >", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleGreaterThanOrEqualTo(String value) {
            addCriterion("light_title >=", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleLessThan(String value) {
            addCriterion("light_title <", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleLessThanOrEqualTo(String value) {
            addCriterion("light_title <=", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleLike(String value) {
            addCriterion("light_title like", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotLike(String value) {
            addCriterion("light_title not like", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleIn(List<String> values) {
            addCriterion("light_title in", values, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotIn(List<String> values) {
            addCriterion("light_title not in", values, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleBetween(String value1, String value2) {
            addCriterion("light_title between", value1, value2, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotBetween(String value1, String value2) {
            addCriterion("light_title not between", value1, value2, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLoanFloorIsNull() {
            addCriterion("loan_floor is null");
            return (Criteria) this;
        }

        public Criteria andLoanFloorIsNotNull() {
            addCriterion("loan_floor is not null");
            return (Criteria) this;
        }

        public Criteria andLoanFloorEqualTo(Integer value) {
            addCriterion("loan_floor =", value, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorNotEqualTo(Integer value) {
            addCriterion("loan_floor <>", value, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorGreaterThan(Integer value) {
            addCriterion("loan_floor >", value, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_floor >=", value, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorLessThan(Integer value) {
            addCriterion("loan_floor <", value, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorLessThanOrEqualTo(Integer value) {
            addCriterion("loan_floor <=", value, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorIn(List<Integer> values) {
            addCriterion("loan_floor in", values, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorNotIn(List<Integer> values) {
            addCriterion("loan_floor not in", values, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorBetween(Integer value1, Integer value2) {
            addCriterion("loan_floor between", value1, value2, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanFloorNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_floor not between", value1, value2, "loanFloor");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingIsNull() {
            addCriterion("loan_ceiling is null");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingIsNotNull() {
            addCriterion("loan_ceiling is not null");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingEqualTo(Integer value) {
            addCriterion("loan_ceiling =", value, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingNotEqualTo(Integer value) {
            addCriterion("loan_ceiling <>", value, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingGreaterThan(Integer value) {
            addCriterion("loan_ceiling >", value, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_ceiling >=", value, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingLessThan(Integer value) {
            addCriterion("loan_ceiling <", value, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingLessThanOrEqualTo(Integer value) {
            addCriterion("loan_ceiling <=", value, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingIn(List<Integer> values) {
            addCriterion("loan_ceiling in", values, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingNotIn(List<Integer> values) {
            addCriterion("loan_ceiling not in", values, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingBetween(Integer value1, Integer value2) {
            addCriterion("loan_ceiling between", value1, value2, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andLoanCeilingNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_ceiling not between", value1, value2, "loanCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationFloorIsNull() {
            addCriterion("duration_floor is null");
            return (Criteria) this;
        }

        public Criteria andDurationFloorIsNotNull() {
            addCriterion("duration_floor is not null");
            return (Criteria) this;
        }

        public Criteria andDurationFloorEqualTo(Integer value) {
            addCriterion("duration_floor =", value, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorNotEqualTo(Integer value) {
            addCriterion("duration_floor <>", value, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorGreaterThan(Integer value) {
            addCriterion("duration_floor >", value, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration_floor >=", value, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorLessThan(Integer value) {
            addCriterion("duration_floor <", value, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorLessThanOrEqualTo(Integer value) {
            addCriterion("duration_floor <=", value, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorIn(List<Integer> values) {
            addCriterion("duration_floor in", values, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorNotIn(List<Integer> values) {
            addCriterion("duration_floor not in", values, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorBetween(Integer value1, Integer value2) {
            addCriterion("duration_floor between", value1, value2, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationFloorNotBetween(Integer value1, Integer value2) {
            addCriterion("duration_floor not between", value1, value2, "durationFloor");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingIsNull() {
            addCriterion("duration_ceiling is null");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingIsNotNull() {
            addCriterion("duration_ceiling is not null");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingEqualTo(Integer value) {
            addCriterion("duration_ceiling =", value, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingNotEqualTo(Integer value) {
            addCriterion("duration_ceiling <>", value, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingGreaterThan(Integer value) {
            addCriterion("duration_ceiling >", value, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration_ceiling >=", value, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingLessThan(Integer value) {
            addCriterion("duration_ceiling <", value, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingLessThanOrEqualTo(Integer value) {
            addCriterion("duration_ceiling <=", value, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingIn(List<Integer> values) {
            addCriterion("duration_ceiling in", values, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingNotIn(List<Integer> values) {
            addCriterion("duration_ceiling not in", values, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingBetween(Integer value1, Integer value2) {
            addCriterion("duration_ceiling between", value1, value2, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andDurationCeilingNotBetween(Integer value1, Integer value2) {
            addCriterion("duration_ceiling not between", value1, value2, "durationCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestFloorIsNull() {
            addCriterion("interest_floor is null");
            return (Criteria) this;
        }

        public Criteria andInterestFloorIsNotNull() {
            addCriterion("interest_floor is not null");
            return (Criteria) this;
        }

        public Criteria andInterestFloorEqualTo(Double value) {
            addCriterion("interest_floor =", value, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorNotEqualTo(Double value) {
            addCriterion("interest_floor <>", value, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorGreaterThan(Double value) {
            addCriterion("interest_floor >", value, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorGreaterThanOrEqualTo(Double value) {
            addCriterion("interest_floor >=", value, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorLessThan(Double value) {
            addCriterion("interest_floor <", value, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorLessThanOrEqualTo(Double value) {
            addCriterion("interest_floor <=", value, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorIn(List<Double> values) {
            addCriterion("interest_floor in", values, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorNotIn(List<Double> values) {
            addCriterion("interest_floor not in", values, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorBetween(Double value1, Double value2) {
            addCriterion("interest_floor between", value1, value2, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestFloorNotBetween(Double value1, Double value2) {
            addCriterion("interest_floor not between", value1, value2, "interestFloor");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingIsNull() {
            addCriterion("interest_ceiling is null");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingIsNotNull() {
            addCriterion("interest_ceiling is not null");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingEqualTo(Double value) {
            addCriterion("interest_ceiling =", value, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingNotEqualTo(Double value) {
            addCriterion("interest_ceiling <>", value, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingGreaterThan(Double value) {
            addCriterion("interest_ceiling >", value, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingGreaterThanOrEqualTo(Double value) {
            addCriterion("interest_ceiling >=", value, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingLessThan(Double value) {
            addCriterion("interest_ceiling <", value, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingLessThanOrEqualTo(Double value) {
            addCriterion("interest_ceiling <=", value, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingIn(List<Double> values) {
            addCriterion("interest_ceiling in", values, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingNotIn(List<Double> values) {
            addCriterion("interest_ceiling not in", values, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingBetween(Double value1, Double value2) {
            addCriterion("interest_ceiling between", value1, value2, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andInterestCeilingNotBetween(Double value1, Double value2) {
            addCriterion("interest_ceiling not between", value1, value2, "interestCeiling");
            return (Criteria) this;
        }

        public Criteria andCreditAuthIsNull() {
            addCriterion("credit_auth is null");
            return (Criteria) this;
        }

        public Criteria andCreditAuthIsNotNull() {
            addCriterion("credit_auth is not null");
            return (Criteria) this;
        }

        public Criteria andCreditAuthEqualTo(String value) {
            addCriterion("credit_auth =", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotEqualTo(String value) {
            addCriterion("credit_auth <>", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthGreaterThan(String value) {
            addCriterion("credit_auth >", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthGreaterThanOrEqualTo(String value) {
            addCriterion("credit_auth >=", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthLessThan(String value) {
            addCriterion("credit_auth <", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthLessThanOrEqualTo(String value) {
            addCriterion("credit_auth <=", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthLike(String value) {
            addCriterion("credit_auth like", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotLike(String value) {
            addCriterion("credit_auth not like", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthIn(List<String> values) {
            addCriterion("credit_auth in", values, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotIn(List<String> values) {
            addCriterion("credit_auth not in", values, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthBetween(String value1, String value2) {
            addCriterion("credit_auth between", value1, value2, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotBetween(String value1, String value2) {
            addCriterion("credit_auth not between", value1, value2, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andLenderNameIsNull() {
            addCriterion("lender_name is null");
            return (Criteria) this;
        }

        public Criteria andLenderNameIsNotNull() {
            addCriterion("lender_name is not null");
            return (Criteria) this;
        }

        public Criteria andLenderNameEqualTo(String value) {
            addCriterion("lender_name =", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotEqualTo(String value) {
            addCriterion("lender_name <>", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameGreaterThan(String value) {
            addCriterion("lender_name >", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameGreaterThanOrEqualTo(String value) {
            addCriterion("lender_name >=", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameLessThan(String value) {
            addCriterion("lender_name <", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameLessThanOrEqualTo(String value) {
            addCriterion("lender_name <=", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameLike(String value) {
            addCriterion("lender_name like", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotLike(String value) {
            addCriterion("lender_name not like", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameIn(List<String> values) {
            addCriterion("lender_name in", values, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotIn(List<String> values) {
            addCriterion("lender_name not in", values, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameBetween(String value1, String value2) {
            addCriterion("lender_name between", value1, value2, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotBetween(String value1, String value2) {
            addCriterion("lender_name not between", value1, value2, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderDescIsNull() {
            addCriterion("lender_desc is null");
            return (Criteria) this;
        }

        public Criteria andLenderDescIsNotNull() {
            addCriterion("lender_desc is not null");
            return (Criteria) this;
        }

        public Criteria andLenderDescEqualTo(String value) {
            addCriterion("lender_desc =", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotEqualTo(String value) {
            addCriterion("lender_desc <>", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescGreaterThan(String value) {
            addCriterion("lender_desc >", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescGreaterThanOrEqualTo(String value) {
            addCriterion("lender_desc >=", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescLessThan(String value) {
            addCriterion("lender_desc <", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescLessThanOrEqualTo(String value) {
            addCriterion("lender_desc <=", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescLike(String value) {
            addCriterion("lender_desc like", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotLike(String value) {
            addCriterion("lender_desc not like", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescIn(List<String> values) {
            addCriterion("lender_desc in", values, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotIn(List<String> values) {
            addCriterion("lender_desc not in", values, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescBetween(String value1, String value2) {
            addCriterion("lender_desc between", value1, value2, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotBetween(String value1, String value2) {
            addCriterion("lender_desc not between", value1, value2, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlIsNull() {
            addCriterion("active_captcha_url is null");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlIsNotNull() {
            addCriterion("active_captcha_url is not null");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlEqualTo(String value) {
            addCriterion("active_captcha_url =", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotEqualTo(String value) {
            addCriterion("active_captcha_url <>", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlGreaterThan(String value) {
            addCriterion("active_captcha_url >", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlGreaterThanOrEqualTo(String value) {
            addCriterion("active_captcha_url >=", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlLessThan(String value) {
            addCriterion("active_captcha_url <", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlLessThanOrEqualTo(String value) {
            addCriterion("active_captcha_url <=", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlLike(String value) {
            addCriterion("active_captcha_url like", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotLike(String value) {
            addCriterion("active_captcha_url not like", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlIn(List<String> values) {
            addCriterion("active_captcha_url in", values, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotIn(List<String> values) {
            addCriterion("active_captcha_url not in", values, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlBetween(String value1, String value2) {
            addCriterion("active_captcha_url between", value1, value2, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotBetween(String value1, String value2) {
            addCriterion("active_captcha_url not between", value1, value2, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlIsNull() {
            addCriterion("reg_interface_url is null");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlIsNotNull() {
            addCriterion("reg_interface_url is not null");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlEqualTo(String value) {
            addCriterion("reg_interface_url =", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotEqualTo(String value) {
            addCriterion("reg_interface_url <>", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlGreaterThan(String value) {
            addCriterion("reg_interface_url >", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("reg_interface_url >=", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlLessThan(String value) {
            addCriterion("reg_interface_url <", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlLessThanOrEqualTo(String value) {
            addCriterion("reg_interface_url <=", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlLike(String value) {
            addCriterion("reg_interface_url like", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotLike(String value) {
            addCriterion("reg_interface_url not like", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlIn(List<String> values) {
            addCriterion("reg_interface_url in", values, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotIn(List<String> values) {
            addCriterion("reg_interface_url not in", values, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlBetween(String value1, String value2) {
            addCriterion("reg_interface_url between", value1, value2, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotBetween(String value1, String value2) {
            addCriterion("reg_interface_url not between", value1, value2, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNull() {
            addCriterion("publish_time is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNotNull() {
            addCriterion("publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeEqualTo(Date value) {
            addCriterion("publish_time =", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotEqualTo(Date value) {
            addCriterion("publish_time <>", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThan(Date value) {
            addCriterion("publish_time >", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_time >=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThan(Date value) {
            addCriterion("publish_time <", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("publish_time <=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIn(List<Date> values) {
            addCriterion("publish_time in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotIn(List<Date> values) {
            addCriterion("publish_time not in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeBetween(Date value1, Date value2) {
            addCriterion("publish_time between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("publish_time not between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeIsNull() {
            addCriterion("unpublish_time is null");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeIsNotNull() {
            addCriterion("unpublish_time is not null");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeEqualTo(Date value) {
            addCriterion("unpublish_time =", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeNotEqualTo(Date value) {
            addCriterion("unpublish_time <>", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeGreaterThan(Date value) {
            addCriterion("unpublish_time >", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("unpublish_time >=", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeLessThan(Date value) {
            addCriterion("unpublish_time <", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("unpublish_time <=", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeIn(List<Date> values) {
            addCriterion("unpublish_time in", values, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeNotIn(List<Date> values) {
            addCriterion("unpublish_time not in", values, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeBetween(Date value1, Date value2) {
            addCriterion("unpublish_time between", value1, value2, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("unpublish_time not between", value1, value2, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeIsNull() {
            addCriterion("display_type is null");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeIsNotNull() {
            addCriterion("display_type is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeEqualTo(Byte value) {
            addCriterion("display_type =", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeNotEqualTo(Byte value) {
            addCriterion("display_type <>", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeGreaterThan(Byte value) {
            addCriterion("display_type >", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("display_type >=", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeLessThan(Byte value) {
            addCriterion("display_type <", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeLessThanOrEqualTo(Byte value) {
            addCriterion("display_type <=", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeIn(List<Byte> values) {
            addCriterion("display_type in", values, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeNotIn(List<Byte> values) {
            addCriterion("display_type not in", values, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeBetween(Byte value1, Byte value2) {
            addCriterion("display_type between", value1, value2, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("display_type not between", value1, value2, "displayType");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdIsNull() {
            addCriterion("charge_mode_id is null");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdIsNotNull() {
            addCriterion("charge_mode_id is not null");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdEqualTo(Long value) {
            addCriterion("charge_mode_id =", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdNotEqualTo(Long value) {
            addCriterion("charge_mode_id <>", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdGreaterThan(Long value) {
            addCriterion("charge_mode_id >", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("charge_mode_id >=", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdLessThan(Long value) {
            addCriterion("charge_mode_id <", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdLessThanOrEqualTo(Long value) {
            addCriterion("charge_mode_id <=", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdIn(List<Long> values) {
            addCriterion("charge_mode_id in", values, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdNotIn(List<Long> values) {
            addCriterion("charge_mode_id not in", values, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdBetween(Long value1, Long value2) {
            addCriterion("charge_mode_id between", value1, value2, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdNotBetween(Long value1, Long value2) {
            addCriterion("charge_mode_id not between", value1, value2, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andApplyTimesIsNull() {
            addCriterion("apply_times is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimesIsNotNull() {
            addCriterion("apply_times is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimesEqualTo(Integer value) {
            addCriterion("apply_times =", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesNotEqualTo(Integer value) {
            addCriterion("apply_times <>", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesGreaterThan(Integer value) {
            addCriterion("apply_times >", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_times >=", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesLessThan(Integer value) {
            addCriterion("apply_times <", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesLessThanOrEqualTo(Integer value) {
            addCriterion("apply_times <=", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesIn(List<Integer> values) {
            addCriterion("apply_times in", values, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesNotIn(List<Integer> values) {
            addCriterion("apply_times not in", values, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesBetween(Integer value1, Integer value2) {
            addCriterion("apply_times between", value1, value2, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_times not between", value1, value2, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeIsNull() {
            addCriterion("loan_wait_time is null");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeIsNotNull() {
            addCriterion("loan_wait_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeEqualTo(Integer value) {
            addCriterion("loan_wait_time =", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeNotEqualTo(Integer value) {
            addCriterion("loan_wait_time <>", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeGreaterThan(Integer value) {
            addCriterion("loan_wait_time >", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_wait_time >=", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeLessThan(Integer value) {
            addCriterion("loan_wait_time <", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeLessThanOrEqualTo(Integer value) {
            addCriterion("loan_wait_time <=", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeIn(List<Integer> values) {
            addCriterion("loan_wait_time in", values, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeNotIn(List<Integer> values) {
            addCriterion("loan_wait_time not in", values, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeBetween(Integer value1, Integer value2) {
            addCriterion("loan_wait_time between", value1, value2, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_wait_time not between", value1, value2, "loanWaitTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table product
     * @mbg.generated  Tue Dec 12 19:00:13 CST 2017
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 08 11:34:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}