package com.pinganzhiyuan.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.subtitle
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.imgurl
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.targeturl
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private String targeturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.weight
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.closetop
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private Boolean closetop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.lighttitle
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private String lighttitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.property
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.edu
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    private String edu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.subtitle
     *
     * @return the value of product.subtitle
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.subtitle
     *
     * @param subtitle the value for product.subtitle
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.imgurl
     *
     * @return the value of product.imgurl
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.imgurl
     *
     * @param imgurl the value for product.imgurl
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.targeturl
     *
     * @return the value of product.targeturl
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public String getTargeturl() {
        return targeturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.targeturl
     *
     * @param targeturl the value for product.targeturl
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setTargeturl(String targeturl) {
        this.targeturl = targeturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.weight
     *
     * @return the value of product.weight
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.weight
     *
     * @param weight the value for product.weight
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.closetop
     *
     * @return the value of product.closetop
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public Boolean getClosetop() {
        return closetop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.closetop
     *
     * @param closetop the value for product.closetop
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setClosetop(Boolean closetop) {
        this.closetop = closetop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.lighttitle
     *
     * @return the value of product.lighttitle
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public String getLighttitle() {
        return lighttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.lighttitle
     *
     * @param lighttitle the value for product.lighttitle
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setLighttitle(String lighttitle) {
        this.lighttitle = lighttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.property
     *
     * @return the value of product.property
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.property
     *
     * @param property the value for product.property
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setProperty(String property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.edu
     *
     * @return the value of product.edu
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public String getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.edu
     *
     * @param edu the value for product.edu
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    public void setEdu(String edu) {
        this.edu = edu;
    }
}