package com.pinganzhiyuan.model;

import java.util.Date;

public class StDevice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.device_id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.regist_time
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private Date registTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.app_name
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String appName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.app_channel
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String appChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.app_version
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String appVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.package_name
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.channel_id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private Long channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.d_ip
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String dIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.d_latitude
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String dLatitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.d_longitude
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String dLongitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.d_brand
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String dBrand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.d_version
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String dVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column st_device.d_user_agent
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	private String dUserAgent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.id
	 * @return  the value of st_device.id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.id
	 * @param id  the value for st_device.id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.device_id
	 * @return  the value of st_device.device_id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.device_id
	 * @param deviceId  the value for st_device.device_id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.regist_time
	 * @return  the value of st_device.regist_time
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public Date getRegistTime() {
		return registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.regist_time
	 * @param registTime  the value for st_device.regist_time
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setRegistTime(Date registTime) {
		this.registTime = registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.app_name
	 * @return  the value of st_device.app_name
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.app_name
	 * @param appName  the value for st_device.app_name
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setAppName(String appName) {
		this.appName = appName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.app_channel
	 * @return  the value of st_device.app_channel
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getAppChannel() {
		return appChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.app_channel
	 * @param appChannel  the value for st_device.app_channel
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setAppChannel(String appChannel) {
		this.appChannel = appChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.app_version
	 * @return  the value of st_device.app_version
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getAppVersion() {
		return appVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.app_version
	 * @param appVersion  the value for st_device.app_version
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.package_name
	 * @return  the value of st_device.package_name
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.package_name
	 * @param packageName  the value for st_device.package_name
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.channel_id
	 * @return  the value of st_device.channel_id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public Long getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.channel_id
	 * @param channelId  the value for st_device.channel_id
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.d_ip
	 * @return  the value of st_device.d_ip
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getdIp() {
		return dIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.d_ip
	 * @param dIp  the value for st_device.d_ip
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setdIp(String dIp) {
		this.dIp = dIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.d_latitude
	 * @return  the value of st_device.d_latitude
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getdLatitude() {
		return dLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.d_latitude
	 * @param dLatitude  the value for st_device.d_latitude
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setdLatitude(String dLatitude) {
		this.dLatitude = dLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.d_longitude
	 * @return  the value of st_device.d_longitude
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getdLongitude() {
		return dLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.d_longitude
	 * @param dLongitude  the value for st_device.d_longitude
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setdLongitude(String dLongitude) {
		this.dLongitude = dLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.d_brand
	 * @return  the value of st_device.d_brand
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getdBrand() {
		return dBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.d_brand
	 * @param dBrand  the value for st_device.d_brand
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setdBrand(String dBrand) {
		this.dBrand = dBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.d_version
	 * @return  the value of st_device.d_version
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getdVersion() {
		return dVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.d_version
	 * @param dVersion  the value for st_device.d_version
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setdVersion(String dVersion) {
		this.dVersion = dVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column st_device.d_user_agent
	 * @return  the value of st_device.d_user_agent
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public String getdUserAgent() {
		return dUserAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column st_device.d_user_agent
	 * @param dUserAgent  the value for st_device.d_user_agent
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	public void setdUserAgent(String dUserAgent) {
		this.dUserAgent = dUserAgent;
	}
}