package com.pinganzhiyuan.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StDeviceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public StDeviceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("device_id like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("device_id not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIsNull() {
            addCriterion("regist_time is null");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIsNotNull() {
            addCriterion("regist_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegistTimeEqualTo(Date value) {
            addCriterion("regist_time =", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotEqualTo(Date value) {
            addCriterion("regist_time <>", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeGreaterThan(Date value) {
            addCriterion("regist_time >", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("regist_time >=", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeLessThan(Date value) {
            addCriterion("regist_time <", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeLessThanOrEqualTo(Date value) {
            addCriterion("regist_time <=", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIn(List<Date> values) {
            addCriterion("regist_time in", values, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotIn(List<Date> values) {
            addCriterion("regist_time not in", values, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeBetween(Date value1, Date value2) {
            addCriterion("regist_time between", value1, value2, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotBetween(Date value1, Date value2) {
            addCriterion("regist_time not between", value1, value2, "registTime");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNull() {
            addCriterion("app_name is null");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNotNull() {
            addCriterion("app_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppNameEqualTo(String value) {
            addCriterion("app_name =", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotEqualTo(String value) {
            addCriterion("app_name <>", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThan(String value) {
            addCriterion("app_name >", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_name >=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThan(String value) {
            addCriterion("app_name <", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThanOrEqualTo(String value) {
            addCriterion("app_name <=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLike(String value) {
            addCriterion("app_name like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotLike(String value) {
            addCriterion("app_name not like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameIn(List<String> values) {
            addCriterion("app_name in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotIn(List<String> values) {
            addCriterion("app_name not in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameBetween(String value1, String value2) {
            addCriterion("app_name between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotBetween(String value1, String value2) {
            addCriterion("app_name not between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppChannelIsNull() {
            addCriterion("app_channel is null");
            return (Criteria) this;
        }

        public Criteria andAppChannelIsNotNull() {
            addCriterion("app_channel is not null");
            return (Criteria) this;
        }

        public Criteria andAppChannelEqualTo(String value) {
            addCriterion("app_channel =", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelNotEqualTo(String value) {
            addCriterion("app_channel <>", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelGreaterThan(String value) {
            addCriterion("app_channel >", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelGreaterThanOrEqualTo(String value) {
            addCriterion("app_channel >=", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelLessThan(String value) {
            addCriterion("app_channel <", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelLessThanOrEqualTo(String value) {
            addCriterion("app_channel <=", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelLike(String value) {
            addCriterion("app_channel like", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelNotLike(String value) {
            addCriterion("app_channel not like", value, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelIn(List<String> values) {
            addCriterion("app_channel in", values, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelNotIn(List<String> values) {
            addCriterion("app_channel not in", values, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelBetween(String value1, String value2) {
            addCriterion("app_channel between", value1, value2, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppChannelNotBetween(String value1, String value2) {
            addCriterion("app_channel not between", value1, value2, "appChannel");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNull() {
            addCriterion("app_version is null");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNotNull() {
            addCriterion("app_version is not null");
            return (Criteria) this;
        }

        public Criteria andAppVersionEqualTo(String value) {
            addCriterion("app_version =", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotEqualTo(String value) {
            addCriterion("app_version <>", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThan(String value) {
            addCriterion("app_version >", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThanOrEqualTo(String value) {
            addCriterion("app_version >=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThan(String value) {
            addCriterion("app_version <", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThanOrEqualTo(String value) {
            addCriterion("app_version <=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLike(String value) {
            addCriterion("app_version like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotLike(String value) {
            addCriterion("app_version not like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionIn(List<String> values) {
            addCriterion("app_version in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotIn(List<String> values) {
            addCriterion("app_version not in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionBetween(String value1, String value2) {
            addCriterion("app_version between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotBetween(String value1, String value2) {
            addCriterion("app_version not between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNull() {
            addCriterion("package_name is null");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNotNull() {
            addCriterion("package_name is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNameEqualTo(String value) {
            addCriterion("package_name =", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotEqualTo(String value) {
            addCriterion("package_name <>", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThan(String value) {
            addCriterion("package_name >", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
            addCriterion("package_name >=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThan(String value) {
            addCriterion("package_name <", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThanOrEqualTo(String value) {
            addCriterion("package_name <=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLike(String value) {
            addCriterion("package_name like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotLike(String value) {
            addCriterion("package_name not like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameIn(List<String> values) {
            addCriterion("package_name in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotIn(List<String> values) {
            addCriterion("package_name not in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameBetween(String value1, String value2) {
            addCriterion("package_name between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotBetween(String value1, String value2) {
            addCriterion("package_name not between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(Long value) {
            addCriterion("channel_id =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(Long value) {
            addCriterion("channel_id <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(Long value) {
            addCriterion("channel_id >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("channel_id >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(Long value) {
            addCriterion("channel_id <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Long value) {
            addCriterion("channel_id <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<Long> values) {
            addCriterion("channel_id in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<Long> values) {
            addCriterion("channel_id not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(Long value1, Long value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(Long value1, Long value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andDIpIsNull() {
            addCriterion("d_ip is null");
            return (Criteria) this;
        }

        public Criteria andDIpIsNotNull() {
            addCriterion("d_ip is not null");
            return (Criteria) this;
        }

        public Criteria andDIpEqualTo(String value) {
            addCriterion("d_ip =", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpNotEqualTo(String value) {
            addCriterion("d_ip <>", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpGreaterThan(String value) {
            addCriterion("d_ip >", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpGreaterThanOrEqualTo(String value) {
            addCriterion("d_ip >=", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpLessThan(String value) {
            addCriterion("d_ip <", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpLessThanOrEqualTo(String value) {
            addCriterion("d_ip <=", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpLike(String value) {
            addCriterion("d_ip like", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpNotLike(String value) {
            addCriterion("d_ip not like", value, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpIn(List<String> values) {
            addCriterion("d_ip in", values, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpNotIn(List<String> values) {
            addCriterion("d_ip not in", values, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpBetween(String value1, String value2) {
            addCriterion("d_ip between", value1, value2, "dIp");
            return (Criteria) this;
        }

        public Criteria andDIpNotBetween(String value1, String value2) {
            addCriterion("d_ip not between", value1, value2, "dIp");
            return (Criteria) this;
        }

        public Criteria andDLatitudeIsNull() {
            addCriterion("d_latitude is null");
            return (Criteria) this;
        }

        public Criteria andDLatitudeIsNotNull() {
            addCriterion("d_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andDLatitudeEqualTo(String value) {
            addCriterion("d_latitude =", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeNotEqualTo(String value) {
            addCriterion("d_latitude <>", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeGreaterThan(String value) {
            addCriterion("d_latitude >", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("d_latitude >=", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeLessThan(String value) {
            addCriterion("d_latitude <", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeLessThanOrEqualTo(String value) {
            addCriterion("d_latitude <=", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeLike(String value) {
            addCriterion("d_latitude like", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeNotLike(String value) {
            addCriterion("d_latitude not like", value, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeIn(List<String> values) {
            addCriterion("d_latitude in", values, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeNotIn(List<String> values) {
            addCriterion("d_latitude not in", values, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeBetween(String value1, String value2) {
            addCriterion("d_latitude between", value1, value2, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLatitudeNotBetween(String value1, String value2) {
            addCriterion("d_latitude not between", value1, value2, "dLatitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeIsNull() {
            addCriterion("d_longitude is null");
            return (Criteria) this;
        }

        public Criteria andDLongitudeIsNotNull() {
            addCriterion("d_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andDLongitudeEqualTo(String value) {
            addCriterion("d_longitude =", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeNotEqualTo(String value) {
            addCriterion("d_longitude <>", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeGreaterThan(String value) {
            addCriterion("d_longitude >", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("d_longitude >=", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeLessThan(String value) {
            addCriterion("d_longitude <", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeLessThanOrEqualTo(String value) {
            addCriterion("d_longitude <=", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeLike(String value) {
            addCriterion("d_longitude like", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeNotLike(String value) {
            addCriterion("d_longitude not like", value, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeIn(List<String> values) {
            addCriterion("d_longitude in", values, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeNotIn(List<String> values) {
            addCriterion("d_longitude not in", values, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeBetween(String value1, String value2) {
            addCriterion("d_longitude between", value1, value2, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDLongitudeNotBetween(String value1, String value2) {
            addCriterion("d_longitude not between", value1, value2, "dLongitude");
            return (Criteria) this;
        }

        public Criteria andDBrandIsNull() {
            addCriterion("d_brand is null");
            return (Criteria) this;
        }

        public Criteria andDBrandIsNotNull() {
            addCriterion("d_brand is not null");
            return (Criteria) this;
        }

        public Criteria andDBrandEqualTo(String value) {
            addCriterion("d_brand =", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandNotEqualTo(String value) {
            addCriterion("d_brand <>", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandGreaterThan(String value) {
            addCriterion("d_brand >", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandGreaterThanOrEqualTo(String value) {
            addCriterion("d_brand >=", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandLessThan(String value) {
            addCriterion("d_brand <", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandLessThanOrEqualTo(String value) {
            addCriterion("d_brand <=", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandLike(String value) {
            addCriterion("d_brand like", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandNotLike(String value) {
            addCriterion("d_brand not like", value, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandIn(List<String> values) {
            addCriterion("d_brand in", values, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandNotIn(List<String> values) {
            addCriterion("d_brand not in", values, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandBetween(String value1, String value2) {
            addCriterion("d_brand between", value1, value2, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDBrandNotBetween(String value1, String value2) {
            addCriterion("d_brand not between", value1, value2, "dBrand");
            return (Criteria) this;
        }

        public Criteria andDVersionIsNull() {
            addCriterion("d_version is null");
            return (Criteria) this;
        }

        public Criteria andDVersionIsNotNull() {
            addCriterion("d_version is not null");
            return (Criteria) this;
        }

        public Criteria andDVersionEqualTo(String value) {
            addCriterion("d_version =", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionNotEqualTo(String value) {
            addCriterion("d_version <>", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionGreaterThan(String value) {
            addCriterion("d_version >", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionGreaterThanOrEqualTo(String value) {
            addCriterion("d_version >=", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionLessThan(String value) {
            addCriterion("d_version <", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionLessThanOrEqualTo(String value) {
            addCriterion("d_version <=", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionLike(String value) {
            addCriterion("d_version like", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionNotLike(String value) {
            addCriterion("d_version not like", value, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionIn(List<String> values) {
            addCriterion("d_version in", values, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionNotIn(List<String> values) {
            addCriterion("d_version not in", values, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionBetween(String value1, String value2) {
            addCriterion("d_version between", value1, value2, "dVersion");
            return (Criteria) this;
        }

        public Criteria andDVersionNotBetween(String value1, String value2) {
            addCriterion("d_version not between", value1, value2, "dVersion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_device
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 29 16:22:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_device
     *
     * @mbg.generated Thu Mar 29 16:22:47 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}