package com.pinganzhiyuan.model;

public class Tab {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tab.id
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tab.name
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tab.icon_url
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    private String iconUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tab.channel_id
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    private Long channelId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tab.package_name
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    private String packageName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tab.version
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    private Integer version;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tab.sequence
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    private Byte sequence;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tab.id
     * @return  the value of tab.id
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tab.id
     * @param id  the value for tab.id
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tab.name
     * @return  the value of tab.name
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tab.name
     * @param name  the value for tab.name
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tab.icon_url
     * @return  the value of tab.icon_url
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tab.icon_url
     * @param iconUrl  the value for tab.icon_url
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tab.channel_id
     * @return  the value of tab.channel_id
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tab.channel_id
     * @param channelId  the value for tab.channel_id
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tab.package_name
     * @return  the value of tab.package_name
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tab.package_name
     * @param packageName  the value for tab.package_name
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tab.version
     * @return  the value of tab.version
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tab.version
     * @param version  the value for tab.version
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tab.sequence
     * @return  the value of tab.sequence
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public Byte getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tab.sequence
     * @param sequence  the value for tab.sequence
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    public void setSequence(Byte sequence) {
        this.sequence = sequence;
    }
}