package com.pinganzhiyuan.model;

public class TabModuleMapping {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.module_id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private Long moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.name
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.icon_url
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private String iconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.scheme_url
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private String schemeUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.channel_id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private Long channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.package_name
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.version
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_module_mapping.sequence
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	private Byte sequence;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.id
	 * @return  the value of tab_module_mapping.id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.id
	 * @param id  the value for tab_module_mapping.id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.module_id
	 * @return  the value of tab_module_mapping.module_id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public Long getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.module_id
	 * @param moduleId  the value for tab_module_mapping.module_id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setModuleId(Long moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.name
	 * @return  the value of tab_module_mapping.name
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.name
	 * @param name  the value for tab_module_mapping.name
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.icon_url
	 * @return  the value of tab_module_mapping.icon_url
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public String getIconUrl() {
		return iconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.icon_url
	 * @param iconUrl  the value for tab_module_mapping.icon_url
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.scheme_url
	 * @return  the value of tab_module_mapping.scheme_url
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public String getSchemeUrl() {
		return schemeUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.scheme_url
	 * @param schemeUrl  the value for tab_module_mapping.scheme_url
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setSchemeUrl(String schemeUrl) {
		this.schemeUrl = schemeUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.channel_id
	 * @return  the value of tab_module_mapping.channel_id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public Long getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.channel_id
	 * @param channelId  the value for tab_module_mapping.channel_id
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.package_name
	 * @return  the value of tab_module_mapping.package_name
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.package_name
	 * @param packageName  the value for tab_module_mapping.package_name
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.version
	 * @return  the value of tab_module_mapping.version
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.version
	 * @param version  the value for tab_module_mapping.version
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_module_mapping.sequence
	 * @return  the value of tab_module_mapping.sequence
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public Byte getSequence() {
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_module_mapping.sequence
	 * @param sequence  the value for tab_module_mapping.sequence
	 * @mbg.generated  Tue Mar 13 17:05:25 CST 2018
	 */
	public void setSequence(Byte sequence) {
		this.sequence = sequence;
	}
}