package com.pinganzhiyuan.model;

public class TabModuleMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_module_mapping.id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_module_mapping.module_id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    private Long moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_module_mapping.channel_id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    private Long channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_module_mapping.package_name
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    private String packageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_module_mapping.version
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_module_mapping.sequence
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    private Byte sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_module_mapping.id
     *
     * @return the value of tab_module_mapping.id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_module_mapping.id
     *
     * @param id the value for tab_module_mapping.id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_module_mapping.module_id
     *
     * @return the value of tab_module_mapping.module_id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_module_mapping.module_id
     *
     * @param moduleId the value for tab_module_mapping.module_id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_module_mapping.channel_id
     *
     * @return the value of tab_module_mapping.channel_id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_module_mapping.channel_id
     *
     * @param channelId the value for tab_module_mapping.channel_id
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_module_mapping.package_name
     *
     * @return the value of tab_module_mapping.package_name
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_module_mapping.package_name
     *
     * @param packageName the value for tab_module_mapping.package_name
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_module_mapping.version
     *
     * @return the value of tab_module_mapping.version
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_module_mapping.version
     *
     * @param version the value for tab_module_mapping.version
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_module_mapping.sequence
     *
     * @return the value of tab_module_mapping.sequence
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public Byte getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_module_mapping.sequence
     *
     * @param sequence the value for tab_module_mapping.sequence
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    public void setSequence(Byte sequence) {
        this.sequence = sequence;
    }
}