package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.H5AppClientColumnMapping;
import com.pinganzhiyuan.model.H5AppClientColumnMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface H5AppClientColumnMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    long countByExample(H5AppClientColumnMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    int deleteByExample(H5AppClientColumnMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    @Delete({
        "delete from h5_app_client_column_mapping",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    @Insert({
        "insert into h5_app_client_column_mapping (h5_column_key, h5_client_version_id, ",
        "status)",
        "values (#{h5ColumnKey,jdbcType=VARCHAR}, #{h5ClientVersionId,jdbcType=INTEGER}, ",
        "#{status,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(H5AppClientColumnMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    int insertSelective(H5AppClientColumnMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    List<H5AppClientColumnMapping> selectByExample(H5AppClientColumnMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    @Select({
        "select",
        "id, h5_column_key, h5_client_version_id, status",
        "from h5_app_client_column_mapping",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.pinganzhiyuan.mapper.H5AppClientColumnMappingMapper.BaseResultMap")
    H5AppClientColumnMapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") H5AppClientColumnMapping record, @Param("example") H5AppClientColumnMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    int updateByExample(@Param("record") H5AppClientColumnMapping record, @Param("example") H5AppClientColumnMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    int updateByPrimaryKeySelective(H5AppClientColumnMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h5_app_client_column_mapping
     *
     * @mbg.generated Mon Mar 19 14:11:15 CST 2018
     */
    @Update({
        "update h5_app_client_column_mapping",
        "set h5_column_key = #{h5ColumnKey,jdbcType=VARCHAR},",
          "h5_client_version_id = #{h5ClientVersionId,jdbcType=INTEGER},",
          "status = #{status,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(H5AppClientColumnMapping record);
}