package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.H5Column;
import com.pinganzhiyuan.model.H5ColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface H5ColumnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	long countByExample(H5ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int deleteByExample(H5ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Delete({ "delete from h5_column", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Insert({ "insert into h5_column (h5_column_key, name, ", "title, subtitle, ", "url, icon_url, max)",
			"values (#{h5ColumnKey,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
			"#{title,jdbcType=VARCHAR}, #{subtitle,jdbcType=VARCHAR}, ",
			"#{url,jdbcType=VARCHAR}, #{iconUrl,jdbcType=VARCHAR}, #{max,jdbcType=INTEGER})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(H5Column record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int insertSelective(H5Column record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	List<H5Column> selectByExample(H5ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Select({ "select", "id, h5_column_key, name, title, subtitle, url, icon_url, max", "from h5_column",
			"where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.pinganzhiyuan.mapper.H5ColumnMapper.BaseResultMap")
	H5Column selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int updateByExampleSelective(@Param("record") H5Column record, @Param("example") H5ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int updateByExample(@Param("record") H5Column record, @Param("example") H5ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int updateByPrimaryKeySelective(H5Column record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_column
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Update({ "update h5_column", "set h5_column_key = #{h5ColumnKey,jdbcType=VARCHAR},",
			"name = #{name,jdbcType=VARCHAR},", "title = #{title,jdbcType=VARCHAR},",
			"subtitle = #{subtitle,jdbcType=VARCHAR},", "url = #{url,jdbcType=VARCHAR},",
			"icon_url = #{iconUrl,jdbcType=VARCHAR},", "max = #{max,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(H5Column record);
}