package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.H5ProductClientVersionMapping;
import com.pinganzhiyuan.model.H5ProductClientVersionMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface H5ProductClientVersionMappingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	long countByExample(H5ProductClientVersionMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	int deleteByExample(H5ProductClientVersionMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	@Delete({ "delete from h5_product_client_version_mapping", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	@Insert({ "insert into h5_product_client_version_mapping (h5_client_version_id, product_id, ", "status)",
			"values (#{h5ClientVersionId,jdbcType=BIGINT}, #{productId,jdbcType=INTEGER}, ",
			"#{status,jdbcType=TINYINT})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(H5ProductClientVersionMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	int insertSelective(H5ProductClientVersionMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	List<H5ProductClientVersionMapping> selectByExample(H5ProductClientVersionMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	@Select({ "select", "id, h5_client_version_id, product_id, status", "from h5_product_client_version_mapping",
			"where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.pinganzhiyuan.mapper.H5ProductClientVersionMappingMapper.BaseResultMap")
	H5ProductClientVersionMapping selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	int updateByExampleSelective(@Param("record") H5ProductClientVersionMapping record,
			@Param("example") H5ProductClientVersionMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	int updateByExample(@Param("record") H5ProductClientVersionMapping record,
			@Param("example") H5ProductClientVersionMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	int updateByPrimaryKeySelective(H5ProductClientVersionMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h5_product_client_version_mapping
	 * @mbg.generated  Thu Mar 29 16:22:47 CST 2018
	 */
	@Update({ "update h5_product_client_version_mapping",
			"set h5_client_version_id = #{h5ClientVersionId,jdbcType=BIGINT},",
			"product_id = #{productId,jdbcType=INTEGER},", "status = #{status,jdbcType=TINYINT}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(H5ProductClientVersionMapping record);
}