package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.Product;
import com.pinganzhiyuan.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    @Delete({
        "delete from product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    @Insert({
        "insert into product (title, subtitle, ",
        "imgurl, targeturl, ",
        "weight, closetop, lighttitle, ",
        "property, edu)",
        "values (#{title,jdbcType=VARCHAR}, #{subtitle,jdbcType=VARCHAR}, ",
        "#{imgurl,jdbcType=VARCHAR}, #{targeturl,jdbcType=VARCHAR}, ",
        "#{weight,jdbcType=INTEGER}, #{closetop,jdbcType=BIT}, #{lighttitle,jdbcType=VARCHAR}, ",
        "#{property,jdbcType=VARCHAR}, #{edu,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    @Select({
        "select",
        "id, title, subtitle, imgurl, targeturl, weight, closetop, lighttitle, property, ",
        "edu",
        "from product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.pinganzhiyuan.mapper.ProductMapper.BaseResultMap")
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 04 17:26:16 CST 2017
     */
    @Update({
        "update product",
        "set title = #{title,jdbcType=VARCHAR},",
          "subtitle = #{subtitle,jdbcType=VARCHAR},",
          "imgurl = #{imgurl,jdbcType=VARCHAR},",
          "targeturl = #{targeturl,jdbcType=VARCHAR},",
          "weight = #{weight,jdbcType=INTEGER},",
          "closetop = #{closetop,jdbcType=BIT},",
          "lighttitle = #{lighttitle,jdbcType=VARCHAR},",
          "property = #{property,jdbcType=VARCHAR},",
          "edu = #{edu,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}