package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.StDevice;
import com.pinganzhiyuan.model.StDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StDeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	long countByExample(StDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	int deleteByExample(StDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	@Delete({ "delete from st_device", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	@Insert({ "insert into st_device (device_id, regist_time, ", "app_name, app_channel, ",
			"app_version, package_name, ", "channel_id, d_ip, d_latitude, ", "d_longitude, d_brand, ",
			"d_version, d_user_agent)", "values (#{deviceId,jdbcType=VARCHAR}, #{registTime,jdbcType=TIMESTAMP}, ",
			"#{appName,jdbcType=VARCHAR}, #{appChannel,jdbcType=VARCHAR}, ",
			"#{appVersion,jdbcType=VARCHAR}, #{packageName,jdbcType=VARCHAR}, ",
			"#{channelId,jdbcType=BIGINT}, #{dIp,jdbcType=VARCHAR}, #{dLatitude,jdbcType=VARCHAR}, ",
			"#{dLongitude,jdbcType=VARCHAR}, #{dBrand,jdbcType=VARCHAR}, ",
			"#{dVersion,jdbcType=VARCHAR}, #{dUserAgent,jdbcType=LONGVARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(StDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	int insertSelective(StDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	List<StDevice> selectByExampleWithBLOBs(StDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	List<StDevice> selectByExample(StDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	@Select({ "select", "id, device_id, regist_time, app_name, app_channel, app_version, package_name, ",
			"channel_id, d_ip, d_latitude, d_longitude, d_brand, d_version, d_user_agent", "from st_device",
			"where id = #{id,jdbcType=INTEGER}" })
	@ResultMap("com.pinganzhiyuan.mapper.StDeviceMapper.ResultMapWithBLOBs")
	StDevice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StDevice record, @Param("example") StDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") StDevice record, @Param("example") StDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	int updateByExample(@Param("record") StDevice record, @Param("example") StDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	int updateByPrimaryKeySelective(StDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	@Update({ "update st_device", "set device_id = #{deviceId,jdbcType=VARCHAR},",
			"regist_time = #{registTime,jdbcType=TIMESTAMP},", "app_name = #{appName,jdbcType=VARCHAR},",
			"app_channel = #{appChannel,jdbcType=VARCHAR},", "app_version = #{appVersion,jdbcType=VARCHAR},",
			"package_name = #{packageName,jdbcType=VARCHAR},", "channel_id = #{channelId,jdbcType=BIGINT},",
			"d_ip = #{dIp,jdbcType=VARCHAR},", "d_latitude = #{dLatitude,jdbcType=VARCHAR},",
			"d_longitude = #{dLongitude,jdbcType=VARCHAR},", "d_brand = #{dBrand,jdbcType=VARCHAR},",
			"d_version = #{dVersion,jdbcType=VARCHAR},", "d_user_agent = #{dUserAgent,jdbcType=LONGVARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKeyWithBLOBs(StDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table st_device
	 * @mbg.generated  Wed Apr 04 16:23:39 CST 2018
	 */
	@Update({ "update st_device", "set device_id = #{deviceId,jdbcType=VARCHAR},",
			"regist_time = #{registTime,jdbcType=TIMESTAMP},", "app_name = #{appName,jdbcType=VARCHAR},",
			"app_channel = #{appChannel,jdbcType=VARCHAR},", "app_version = #{appVersion,jdbcType=VARCHAR},",
			"package_name = #{packageName,jdbcType=VARCHAR},", "channel_id = #{channelId,jdbcType=BIGINT},",
			"d_ip = #{dIp,jdbcType=VARCHAR},", "d_latitude = #{dLatitude,jdbcType=VARCHAR},",
			"d_longitude = #{dLongitude,jdbcType=VARCHAR},", "d_brand = #{dBrand,jdbcType=VARCHAR},",
			"d_version = #{dVersion,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(StDevice record);
}