package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.Tab;
import com.pinganzhiyuan.model.TabExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TabMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    long countByExample(TabExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    int deleteByExample(TabExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    @Delete({ "delete from tab", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    @Insert({ "insert into tab (name, icon_url, ", "channel_id, package_name, ", "version, sequence)",
            "values (#{name,jdbcType=VARCHAR}, #{iconUrl,jdbcType=VARCHAR}, ",
            "#{channelId,jdbcType=BIGINT}, #{packageName,jdbcType=VARCHAR}, ",
            "#{version,jdbcType=INTEGER}, #{sequence,jdbcType=TINYINT})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(Tab record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    int insertSelective(Tab record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    List<Tab> selectByExample(TabExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    @Select({ "select", "id, name, icon_url, channel_id, package_name, version, sequence", "from tab",
            "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.pinganzhiyuan.mapper.TabMapper.BaseResultMap")
    Tab selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") Tab record, @Param("example") TabExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    int updateByExample(@Param("record") Tab record, @Param("example") TabExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    int updateByPrimaryKeySelective(Tab record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tab
     * @mbg.generated  Thu Dec 28 10:40:19 CST 2017
     */
    @Update({ "update tab", "set name = #{name,jdbcType=VARCHAR},", "icon_url = #{iconUrl,jdbcType=VARCHAR},",
            "channel_id = #{channelId,jdbcType=BIGINT},", "package_name = #{packageName,jdbcType=VARCHAR},",
            "version = #{version,jdbcType=INTEGER},", "sequence = #{sequence,jdbcType=TINYINT}",
            "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(Tab record);
}