package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.TabModuleMapping;
import com.pinganzhiyuan.model.TabModuleMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TabModuleMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    long countByExample(TabModuleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    int deleteByExample(TabModuleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    @Delete({
        "delete from tab_module_mapping",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    @Insert({
        "insert into tab_module_mapping (module_id, channel_id, ",
        "package_name, version, ",
        "sequence)",
        "values (#{moduleId,jdbcType=BIGINT}, #{channelId,jdbcType=BIGINT}, ",
        "#{packageName,jdbcType=VARCHAR}, #{version,jdbcType=INTEGER}, ",
        "#{sequence,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TabModuleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    int insertSelective(TabModuleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    List<TabModuleMapping> selectByExample(TabModuleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    @Select({
        "select",
        "id, module_id, channel_id, package_name, version, sequence",
        "from tab_module_mapping",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.pinganzhiyuan.mapper.TabModuleMappingMapper.BaseResultMap")
    TabModuleMapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") TabModuleMapping record, @Param("example") TabModuleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    int updateByExample(@Param("record") TabModuleMapping record, @Param("example") TabModuleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    int updateByPrimaryKeySelective(TabModuleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_module_mapping
     *
     * @mbg.generated Fri Dec 29 15:21:02 CST 2017
     */
    @Update({
        "update tab_module_mapping",
        "set module_id = #{moduleId,jdbcType=BIGINT},",
          "channel_id = #{channelId,jdbcType=BIGINT},",
          "package_name = #{packageName,jdbcType=VARCHAR},",
          "version = #{version,jdbcType=INTEGER},",
          "sequence = #{sequence,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TabModuleMapping record);
}