package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.TDConfig;
import com.pinganzhiyuan.model.TDConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TDConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	long countByExample(TDConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int deleteByExample(TDConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Delete({ "delete from td_config", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Insert({ "insert into td_config (package_name, channel_id, ", "threshold)",
			"values (#{packageName,jdbcType=VARCHAR}, #{channelId,jdbcType=BIGINT}, ",
			"#{threshold,jdbcType=INTEGER})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(TDConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int insertSelective(TDConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	List<TDConfig> selectByExample(TDConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Select({ "select", "id, package_name, channel_id, threshold", "from td_config",
			"where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.pinganzhiyuan.mapper.TDConfigMapper.BaseResultMap")
	TDConfig selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TDConfig record, @Param("example") TDConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int updateByExample(@Param("record") TDConfig record, @Param("example") TDConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	int updateByPrimaryKeySelective(TDConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table td_config
	 * @mbg.generated  Mon Mar 19 14:11:15 CST 2018
	 */
	@Update({ "update td_config", "set package_name = #{packageName,jdbcType=VARCHAR},",
			"channel_id = #{channelId,jdbcType=BIGINT},", "threshold = #{threshold,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(TDConfig record);
}